#!/bin/bash

read -p "Are you sure you want to make a file called prettier.config.mjs? ENTER to continue, ^c to exit. ";
touch ./test;
echo "/** @type {import("prettier").Config} */
const config = {
	trailingComma: 'es5',
	tabWidth: 4,
	singleQuote: true,
	plugins: ['prettier-plugin-astro', 'prettier-plugin-tailwindcss'],
	arrowParens: 'avoid',
	proseWrap: 'always',
	// singleAttributePerLine: true,
	experimentalTernaries: true,
	overrides: [
		{
			files: '*.astro',
			options: {
				parser: 'astro',
			},
		},
	],
}

export default config" > ./prettier.config.mjs;
read -p "pnpm add pretter prettier-plugin-astro prettier-plugin-tailwindcss? ENTER to continue, ^c to exit. ";
pnpm add prettier prettier-plugin-astro prettier-plugin-tailwindcss;
